import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { Blob as NodeBlob } from 'node:buffer';
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

// jsdom 的 FileReader 对 readAsArrayBuffer 支持不完整，会让 GLTFExporter 的 binary
// 路径拼出坏字节；此处用 Node 原生 Blob + 薄封装 FileReader 兜底（仅本测试文件生效）。
class NodeFileReader {
  result: unknown = null;
  onloadend: (() => void) | null = null;
  readAsArrayBuffer(blob: Blob): void {
    blob.arrayBuffer().then((buf) => {
      this.result = buf;
      this.onloadend?.();
    });
  }
  readAsDataURL(blob: Blob): void {
    blob.arrayBuffer().then((buf) => {
      this.result = `data:application/octet-stream;base64,${Buffer.from(buf).toString('base64')}`;
      this.onloadend?.();
    });
  }
}

(globalThis as unknown as { Blob: unknown; FileReader: unknown }).Blob = NodeBlob;
(globalThis as unknown as { Blob: unknown; FileReader: unknown }).FileReader = NodeFileReader;
import {
  assertSculptMeshContract,
  createCharacterBaseModel,
  loadCharacterModel,
  NX9_SCULPT_MESH_CONTRACT,
} from '@nx9/director3d';
import type { Group } from 'three';

/**
 * 正式身份基模生成器 + 加载回环契约校验。
 *
 * 每次运行都会用 `procedural-base-model.ts` 重新生成并写入：
 *   apps/web/public/director3d/models/nx9-character-base.glb
 *   apps/web/public/director3d/models/nx9-character-base.manifest.json
 *   apps/web/public/director3d/models/LICENSE-nx9-character-base.txt
 *
 * 然后把它读回来，用运行时真实的 `assertSculptMeshContract` + `loadCharacterModel`
 * 判定是否「builtin」合格，防止生成物与契约漂移。
 */

const MODELS_DIR = path.resolve(process.cwd(), 'public/director3d/models');
const GLB_PATH = path.join(MODELS_DIR, 'nx9-character-base.glb');
const MANIFEST_PATH = path.join(MODELS_DIR, 'nx9-character-base.manifest.json');
const LICENSE_PATH = path.join(MODELS_DIR, 'LICENSE-nx9-character-base.txt');

function parseGlb(bytes: ArrayBuffer): Promise<Group> {
  return new Promise((resolve, reject) => {
    new GLTFLoader().parse(
      bytes,
      '',
      (gltf) => resolve(gltf.scene as Group),
      (err) => reject(err instanceof Error ? err : new Error(String(err))),
    );
  });
}

describe('正式身份基模生成与契约回环', () => {
  it('生成 GLB + manifest + LICENSE，并过加载回环契约校验', async () => {
    // 1. 内存构建并先行校验契约
    const model = createCharacterBaseModel();
    const inMemory = assertSculptMeshContract(model, 'builtin');
    expect(inMemory.viewportSliceMapped).toBe(true);
    expect(inMemory.missingParamIds).toEqual([]);
    expect(inMemory.missingBones).toEqual([]);
    expect(inMemory.hasArmature).toBe(true);
    expect(inMemory.handleCount).toBeGreaterThanOrEqual(9);
    expect(inMemory.warnings.some((w) => w.includes('表情头'))).toBe(false);

    // 2. 导出 GLB（binary）
    const exporter = new GLTFExporter();
    const arrayBuffer = (await exporter.parseAsync(model, { binary: true })) as ArrayBuffer;
    expect(arrayBuffer.byteLength).toBeGreaterThan(1024);

    // 3. 落盘资产三件套
    fs.mkdirSync(MODELS_DIR, { recursive: true });
    fs.writeFileSync(GLB_PATH, Buffer.from(arrayBuffer));
    fs.writeFileSync(
      MANIFEST_PATH,
      JSON.stringify(
        {
          version: 1,
          meshContractVersion: NX9_SCULPT_MESH_CONTRACT,
          modelPath: 'nx9-character-base.glb',
          license: 'NX9 internal',
        },
        null,
        2,
      ) + '\n',
    );
    fs.writeFileSync(
      LICENSE_PATH,
      [
        'NX9 internal character base model (procedural clay).',
        'Contract version: ' + NX9_SCULPT_MESH_CONTRACT,
        'Generated by packages/director3d/src/sculpt/procedural-base-model.ts.',
        'License: NX9 internal use only.',
        '',
      ].join('\n'),
    );

    // 4. 读回并按运行时加载路径校验
    const disk = fs.readFileSync(GLB_PATH);
    const diskBuffer = new ArrayBuffer(disk.byteLength);
    new Uint8Array(diskBuffer).set(disk);
    const loaded = await parseGlb(diskBuffer);

    const report = assertSculptMeshContract(loaded, 'builtin');
    expect(report.viewportSliceMapped).toBe(true);
    expect(report.missingParamIds).toEqual([]);
    expect(report.missingBones).toEqual([]);
    expect(report.handleCount).toBeGreaterThanOrEqual(9);
    expect(report.warnings.some((w) => w.includes('表情头'))).toBe(false);

    const result = await loadCharacterModel({
      fetchManifest: async () => ({
        version: 1,
        meshContractVersion: NX9_SCULPT_MESH_CONTRACT,
        modelPath: 'nx9-character-base.glb',
      }),
      loadGltf: async () => loaded,
    });
    expect(result.source).toBe('builtin');
    expect(result.warnings).toEqual([]);
  }, 30000);
});
