import type { BlockDefinition, BlockCategory } from '../types/block';

const DEV_BLOCKS: BlockDefinition[] = [];

/** NX9 block catalog — §9 trimmed; merged + native kinds */
export const BLOCK_CATALOG: BlockDefinition[] = [
  // ── Source / 素材 ──
  { kind: 'asset-import', label: '素材导入', category: 'source', hint: '图像 / 视频 / 音频 / 3D 上传', glyph: 'Upload', accent: '#2E8B57' },
  { kind: 'mesh-import', label: '3D 导入', category: 'source', hint: 'glb/gltf/obj 等 3D 模型上传', glyph: 'Box', accent: '#5E4D8A', concealed: false },
  { kind: 'mesh-viewer', label: '3D 预览', category: 'source', hint: '3D 模型预览与快照导出', glyph: 'Box', accent: '#5E4D8A', concealed: false },
  { kind: 'asset-bundle', label: '素材集合', category: 'source', hint: '多素材打包（已合并至迭代器）', glyph: 'Images', accent: '#2E8B57', deprecated: true },
  { kind: 'render-slot', label: '渲染占位', category: 'source', hint: '预设落位框（已合并至预览）', glyph: 'ScanLine', accent: '#2E8B57', deprecated: true },
  { kind: 'preview-sink', label: '结果预览', category: 'source', hint: '上游结果终端预览', glyph: 'MonitorPlay', accent: '#2E8B57' },

  // ── Generate / 生成 ──
  { kind: 'prompt', label: '提示词', category: 'generate', hint: '多行提示词 + 上游素材配对，批量出图', glyph: 'Type', accent: '#A13D63' },
  { kind: 'picture-gen', label: '图像生成', category: 'generate', hint: '多模型图像生成', glyph: 'Image', accent: '#A13D63' },
  { kind: 'clip-gen', label: '视频生成', category: 'generate', hint: 'Veo / Grok 等视频生成', glyph: 'Video', accent: '#A13D63' },
  { kind: 'clip-editor', label: '视频剪辑', category: 'generate', hint: '多片段拼接与转场', glyph: 'Scissors', accent: '#A13D63' },
  { kind: 'motion-story', label: '动效分镜', category: 'generate', hint: 'Seedance 2.0 分镜视频', glyph: 'Film', accent: '#A13D63' },
  { kind: 'director-desk', label: '导演台', category: 'generate', hint: '多镜头并发分镜生成', glyph: 'Clapperboard', accent: '#A13D63' },
  {
    kind: 'director-3d',
    label: '3D 导演台',
    category: 'spatial',
    hint: '3D 预演、摆位与截图',
    glyph: 'Box',
    accent: '#5E4D8A',
    nx9Native: true,
  },
  {
    kind: 'blocking-stage',
    label: '场面调度',
    category: 'spatial',
    hint: '轻量 blocking + 机位序列',
    glyph: 'Users',
    accent: '#5E4D8A',
    nx9Native: true,
  },
  {
    kind: 'light-rig',
    label: '灯光方案',
    category: 'spatial',
    hint: 'HDRI / 三点光 preset → prompt',
    glyph: 'Sun',
    accent: '#5E4D8A',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'depth-pass',
    label: '深度通道',
    category: 'spatial',
    hint: '图像 → depth / normal 图',
    glyph: 'Layers',
    accent: '#5E4D8A',
    nx9Native: true,
    concealed: true,
  },
  { kind: 'sound-gen', label: 'AI 配音', category: 'generate', hint: 'TTS / LuxTTS 声线克隆（非 Suno 音乐）', glyph: 'Music', accent: '#A13D63' },
  { kind: 'chat-model', label: '对话模型', category: 'generate', hint: 'LLM 流式对话', glyph: 'Brain', accent: '#A13D63' },
  {
    kind: 'photo-speak',
    label: '照片说话',
    category: 'generate',
    hint: '照片 + 文案 → 口播视频',
    glyph: 'Mic',
    accent: '#A13D63',
    nx9Native: true,
  },

  // ── NX9 生产链（§9.4） ──
  {
    kind: 'shot-script',
    label: '镜头脚本',
    category: 'generate',
    hint: '结构化镜头表 → 故事板 / 导演台',
    glyph: 'ScrollText',
    accent: '#A13D63',
    nx9Native: true,
  },
  {
    kind: 'reference-board',
    label: '参考板',
    category: 'craft',
    hint: 'Mood board + 风格约束 prompt',
    glyph: 'LayoutDashboard',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'character-sheet',
    label: '角色设定',
    category: 'craft',
    hint: '完整设定图 + 档案 + 三视图上传 + 变体',
    glyph: 'UserSquare2',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'continuity-check',
    label: '连贯性检查',
    category: 'craft',
    hint: '多镜头服装/光影/轴线差异报告',
    glyph: 'ScanEye',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'scene-card',
    label: '场景设定卡',
    category: 'craft',
    hint: '场景名、时代、光线、道具 → 场景约束 prompt',
    glyph: 'MapPin',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'dialogue-sheet',
    label: '对白表',
    category: 'craft',
    hint: '从剧本提取对白行，编辑后驱动配音',
    glyph: 'MessageSquareText',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'voice-cast',
    label: '多角色配音',
    category: 'craft',
    hint: '对白表 → 角色音色配置 → 批量 TTS → 绑定镜头',
    glyph: 'Podcast',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'bridge-clip',
    label: 'Bridge 续拍',
    category: 'craft',
    hint: '上一镜视频 + 下一镜 prompt → 抽尾帧 → continuation 参数',
    glyph: 'PictureInPicture2',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'caption-asr',
    label: '语音转字幕',
    category: 'utility',
    hint: '视频/音频 → 自动语音识别 → SRT 字幕',
    glyph: 'Subtitles',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'seedance-chain',
    label: 'Seedance 连续 Clip',
    category: 'generate',
    hint: '按故事板顺序批量生成连续 Clip（自动前情续接）',
    glyph: 'Film',
    accent: '#A13D63',
    nx9Native: true,
  },
  {
    kind: 'thumbnail-maker',
    label: '封面制作',
    category: 'craft',
    hint: '从图片/视频抽帧 → 加标题 → 导出 9:16 封面',
    glyph: 'ImagePlus',
    accent: '#D97706',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'inpaint-edit',
    label: '局部重绘',
    category: 'craft',
    hint: '原图 + 蒙版 + prompt → Fal/Comfy 局部重绘',
    glyph: 'Brush',
    accent: '#D97706',
    nx9Native: true,
    concealed: false,
  },
  {
    kind: 'control-preprocess',
    label: 'ControlNet 预处理',
    category: 'spatial',
    hint: '原图 → depth / canny / pose 控制图（替代 depth-pass）',
    glyph: 'Layers',
    accent: '#5E4D8A',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'reference-analyze',
    label: '参考片反推',
    category: 'utility',
    hint: '参考视频 → 分镜草案 → shot-script',
    glyph: 'Video',
    accent: '#D97706',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'music-gen',
    label: 'BGM 生成',
    category: 'utility',
    hint: '情绪/风格 prompt → BGM 音频（非配音，与 sound-gen 分离）',
    glyph: 'Music',
    accent: '#D97706',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'lipsync-pass',
    label: '口型同步',
    category: 'support',
    hint: '人像视频 + 音频 → 口型同步视频（依赖部署外部模型）',
    glyph: 'ScanFace',
    accent: '#222222',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'export-pack',
    label: '交付打包',
    category: 'utility',
    hint: '成片 / 静帧 / 音频批量导出',
    glyph: 'PackageOpen',
    accent: '#D97706',
    nx9Native: true,
  },

  // ── §9.4 B 音视频后期 ──
  {
    kind: 'subtitle-burn',
    label: '字幕烧录',
    category: 'utility',
    hint: '文本 + 视频 → 带字幕成片（支持 SRT 上传）',
    glyph: 'Subtitles',
    accent: '#A13D63',
    nx9Native: true,
  },
  {
    kind: 'audio-mix',
    label: '音频混音',
    category: 'utility',
    hint: '多轨混音 / 响度归一（单轨失败不拖死全局）',
    glyph: 'AudioLines',
    accent: '#A13D63',
    nx9Native: true,
  },
  {
    kind: 'color-grade',
    label: '调色',
    category: 'utility',
    hint: '亮度 / 对比 / 饱和度',
    glyph: 'Palette',
    accent: '#A13D63',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'beat-sync',
    label: '节拍对齐',
    category: 'utility',
    hint: 'BPM 切点 meta 驱动剪辑',
    glyph: 'Music2',
    accent: '#A13D63',
    nx9Native: true,
    concealed: true,
  },

  // ── §9.4 C 工作流协作 ──
  {
    kind: 'variant-fork',
    label: '方案分叉',
    category: 'support',
    hint: 'A/B 方案标记与 Take 对比',
    glyph: 'GitBranch',
    accent: '#222222',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'review-gate',
    label: '审阅关卡',
    category: 'support',
    hint: '故事板审阅通过后才继续',
    glyph: 'ShieldCheck',
    accent: '#222222',
    nx9Native: true,
  },
  {
    kind: 'recipe-spawn',
    label: '配方一键',
    category: 'support',
    hint: '加载 Rail Recipe 子图',
    glyph: 'LayoutTemplate',
    accent: '#222222',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'prompt-diff',
    label: 'Prompt 对比',
    category: 'craft',
    hint: '多路 prompt diff + 合并建议',
    glyph: 'Diff',
    accent: '#D97706',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'asset-watch',
    label: '素材监听',
    category: 'source',
    hint: 'URL 变更触发下游重跑',
    glyph: 'Radar',
    accent: '#2E8B57',
    nx9Native: true,
    concealed: true,
  },

  // ── Hub (P0 deprecated) ──
  { kind: 'workflow-hub', label: 'Workflow Hub', category: 'hub', hint: '已废弃', glyph: 'Workflow', accent: '#5E4D8A', deprecated: true },
  { kind: 'wallet-hub', label: 'Wallet Hub', category: 'hub', hint: '已废弃', glyph: 'Wallet', accent: '#5E4D8A', deprecated: true },
  { kind: 'param-inject', label: '参数注入', category: 'hub', hint: '已废弃', glyph: 'Settings2', accent: '#5E4D8A', concealed: true, deprecated: true },
  { kind: 'hub-market', label: 'Hub 超市', category: 'hub', hint: '已废弃', glyph: 'Sparkles', accent: '#5E4D8A', deprecated: true },
  { kind: 'hub-toolkit', label: 'Hub 工具箱', category: 'hub', hint: '已废弃', glyph: 'Wrench', accent: '#5E4D8A', deprecated: true },
  { kind: 'vibe-workbench', label: 'Vibe 工作台', category: 'hub', hint: '已废弃', glyph: 'Clapperboard', accent: '#5E4D8A', deprecated: true },
  ...DEV_BLOCKS,

  // ── Integrate ──
  {
    kind: 'model-market',
    label: '模型超市',
    category: 'integrate',
    hint: 'FAL / ComfyUI 模型切换运行',
    glyph: 'Store',
    accent: '#5E4D8A',
    nx9Native: true,
    concealed: true,
  },
  {
    kind: 'comfy-workflow',
    label: 'Comfy 工作流',
    category: 'integrate',
    hint: '提交 ComfyUI Workflow JSON 到服务端运行（concealed）',
    glyph: 'Workflow',
    accent: '#5E4D8A',
    nx9Native: true,
    concealed: true,
  },
  { kind: 'fal-market', label: 'FAL 超市', category: 'integrate', hint: '已合并至模型超市', glyph: 'Store', accent: '#5E4D8A', deprecated: true },
  { kind: 'grok-agent', label: 'Grok Agent', category: 'integrate', hint: '已废弃', glyph: 'Bot', accent: '#5E4D8A', deprecated: true },
  { kind: 'codex-agent', label: 'Codex Agent', category: 'integrate', hint: '已废弃', glyph: 'TerminalSquare', accent: '#5E4D8A', deprecated: true },
  { kind: 'codex-picture', label: 'Codex 生图', category: 'integrate', hint: '已废弃', glyph: 'ImagePlus', accent: '#5E4D8A', deprecated: true },
  { kind: 'comfy-market', label: 'ComfyUI 超市', category: 'integrate', hint: '已合并至模型超市', glyph: 'Boxes', accent: '#5E4D8A', deprecated: true },
  { kind: 'comfy-builder', label: 'ComfyUI 制作', category: 'integrate', hint: '已废弃', glyph: 'FileJson', accent: '#5E4D8A', deprecated: true },

  // ── Craft / 合并节点 ──
  {
    kind: 'prompt-studio',
    label: 'Prompt 工作室',
    category: 'craft',
    hint: '电影感 / 运镜 / 角度 / 肖像 / 姿势',
    glyph: 'Sparkles',
    accent: '#D97706',
    nx9Native: true,
  },
  {
    kind: 'style-lab',
    label: '风格实验室',
    category: 'craft',
    hint: '艺术家风格 + 动漫标签检索',
    glyph: 'Palette',
    accent: '#D97706',
    nx9Native: true,
  },
  { kind: 'cinema-prompt', label: '电影感', category: 'craft', hint: '已合并至 Prompt 工作室', glyph: 'Clapperboard', accent: '#D97706', deprecated: true },
  { kind: 'camera-prompt', label: '运镜', category: 'craft', hint: '已合并至 Prompt 工作室', glyph: 'Camera', accent: '#D97706', deprecated: true },
  { kind: 'angle-visual', label: '多角度', category: 'craft', hint: '已合并至 Prompt 工作室', glyph: 'Compass', accent: '#D97706', deprecated: true },
  { kind: 'portrait-craft', label: '肖像设计', category: 'craft', hint: '已合并至 Prompt 工作室', glyph: 'UserRoundCog', accent: '#D97706', deprecated: true },
  { kind: 'pose-craft', label: '姿势设计', category: 'craft', hint: '已合并至 Prompt 工作室', glyph: 'PersonStanding', accent: '#D97706', deprecated: true },
  { kind: 'style-atelier', label: '风格工坊', category: 'craft', hint: '已合并至风格实验室', glyph: 'Palette', accent: '#D97706', deprecated: true },
  { kind: 'tag-atelier', label: '标签工坊', category: 'craft', hint: '已合并至风格实验室', glyph: 'Tags', accent: '#D97706', deprecated: true },
  {
    kind: 'story-grid',
    label: '分镜网格',
    category: 'craft',
    hint: '分镜九宫格',
    glyph: 'LayoutGrid',
    accent: '#5E4D8A',
    nx9Native: true,
  },
  {
    kind: 'grid-prompt-reverse',
    label: '宫格反推',
    category: 'craft',
    hint: '宫格逐格 Vision 三层 Prompt',
    glyph: 'ScanLine',
    accent: '#5E4D8A',
    nx9Native: true,
  },

  // ── Utility ──
  {
    kind: 'local-enhance',
    label: '本地增强',
    category: 'utility',
    hint: 'Topaz 图像 / 视频高清化',
    glyph: 'ZoomIn',
    accent: '#D97706',
    nx9Native: true,
    concealed: true,
  },
  { kind: 'sketch-pad', label: '画板', category: 'utility', hint: '图层手绘标注', glyph: 'Pencil', accent: '#D97706', concealed: true },
  { kind: 'web-view', label: '网页', category: 'utility', hint: '已废弃', glyph: 'Globe2', accent: '#D97706', concealed: true, deprecated: true },
  { kind: 'picture-diff', label: '图像对比', category: 'utility', hint: '双图对比分析', glyph: 'GitCompare', accent: '#D97706' },
  { kind: 'frame-sampler', label: '抽帧', category: 'utility', hint: '已废弃', glyph: 'Scissors', accent: '#D97706', concealed: true, deprecated: true },
  { kind: 'frame-endpoints', label: '首尾帧', category: 'utility', hint: '视频首帧/尾帧提取', glyph: 'Film', accent: '#D97706' },
  { kind: 'iterator', label: '迭代器', category: 'utility', hint: '串联/并联驱动下游', glyph: 'Repeat', accent: '#D97706' },
  { kind: 'picker', label: '选取器', category: 'utility', hint: '从集合取单项', glyph: 'Filter', accent: '#D97706', concealed: true },
  { kind: 'text-chunker', label: '文本切分', category: 'utility', hint: '长文本分段', glyph: 'SplitSquareVertical', accent: '#D97706' },
  { kind: 'scale-fit', label: '尺寸调整', category: 'utility', hint: '图像缩放', glyph: 'Maximize2', accent: '#D97706', concealed: true },
  { kind: 'picture-merge', label: '图像合并', category: 'utility', hint: '多图合并', glyph: 'Combine', accent: '#D97706', concealed: true },
  { kind: 'bg-remove', label: '抠图', category: 'utility', hint: 'Fal BiRefNet 背景移除', glyph: 'Eraser', accent: '#D97706' },
  { kind: 'upscale-lite', label: '放大', category: 'utility', hint: 'Lanczos 图像放大', glyph: 'ZoomIn', accent: '#D97706', concealed: true },
  { kind: 'grid-split', label: '宫格切分', category: 'utility', hint: '网格切图', glyph: 'Grid3x3', accent: '#D97706' },
  { kind: 'grid-compose', label: '宫格编辑', category: 'utility', hint: '宫格拼接拆分', glyph: 'LayoutGrid', accent: '#D97706' },
  { kind: 'link-parser', label: '素材采集', category: 'utility', hint: '自媒体链接解析为素材', glyph: 'Link2', accent: '#D97706' },
  { kind: 'batch-runner', label: '批量处理', category: 'utility', hint: '批量素材处理', glyph: 'Files', accent: '#D97706', concealed: true },
  { kind: 'topaz-picture', label: 'Topaz 图像', category: 'utility', hint: '已合并至本地增强', glyph: 'Image', accent: '#D97706', deprecated: true },
  { kind: 'topaz-clip', label: 'Topaz 视频', category: 'utility', hint: '已合并至本地增强', glyph: 'Video', accent: '#D97706', deprecated: true },

  // ── Support ──
  { kind: 'touch-up', label: '局部编辑', category: 'support', hint: '已废弃', glyph: 'Edit3', accent: '#222222', concealed: true, deprecated: true },
  { kind: 'memo', label: '备忘', category: 'support', hint: '灵感记录 / 蓝图注释', glyph: 'Lightbulb', accent: '#222222' },
  { kind: 'blueprint', label: '蓝图', category: 'support', hint: '已合并至备忘', glyph: 'Map', accent: '#222222', deprecated: true },
  { kind: 'passthrough', label: '透传', category: 'support', hint: '数据中转（CommandPalette）', glyph: 'ArrowRightLeft', accent: '#222222', concealed: true },
  { kind: 'watermark-clean', label: '去 AI 水印', category: 'support', hint: '水印/元数据清理', glyph: 'ShieldOff', accent: '#222222', concealed: true },
  { kind: 'clip-sink', label: '视频输出', category: 'support', hint: '已废弃', glyph: 'MonitorPlay', accent: '#222222', concealed: true, deprecated: true },

  // ── Spatial ──
  { kind: 'panorama-sphere', label: '3D 全景', category: 'spatial', hint: '360° 全景预览', glyph: 'Globe2', accent: '#5E4D8A', concealed: true },
  { kind: 'multi-view-3d', label: '多角度 3D', category: 'spatial', hint: '已废弃', glyph: 'Box', accent: '#5E4D8A', concealed: true, deprecated: true },
  { kind: 'panorama-flat', label: '720 全景', category: 'spatial', hint: '已废弃', glyph: 'Globe', accent: '#5E4D8A', concealed: true, deprecated: true },
  { kind: 'portrait-flow', label: '肖像流程', category: 'craft', hint: '已废弃', glyph: 'UserSquare2', accent: '#5E4D8A', concealed: true, deprecated: true },
  { kind: 'portrait-meta', label: '肖像元数据', category: 'craft', hint: '已废弃', glyph: 'FileText', accent: '#5E4D8A', concealed: true, deprecated: true },
];

export function isBlockSpawnable(block: BlockDefinition): boolean {
  return !block.deprecated;
}

/** Dock / LensMenu — 精简生产向模块（§9.3 ~28） */
export function isDockVisible(block: BlockDefinition): boolean {
  return isBlockSpawnable(block) && !block.concealed;
}

export function getSpawnableBlocks(): BlockDefinition[] {
  return BLOCK_CATALOG.filter(isBlockSpawnable);
}

export function getDockBlocks(): BlockDefinition[] {
  return BLOCK_CATALOG.filter(isDockVisible);
}

function spawnableInCategory(category: BlockCategory): BlockDefinition[] {
  return BLOCK_CATALOG.filter((b) => b.category === category && isDockVisible(b));
}

export const BLOCK_GROUPS: Record<BlockCategory, { title: string; items: BlockDefinition[] }> = {
  source: { title: '素材', items: spawnableInCategory('source') },
  generate: { title: '生成', items: spawnableInCategory('generate') },
  hub: { title: 'Hub', items: spawnableInCategory('hub') },
  integrate: { title: '集成', items: spawnableInCategory('integrate') },
  craft: { title: '创作', items: spawnableInCategory('craft') },
  utility: { title: '工具', items: spawnableInCategory('utility') },
  support: { title: '辅助', items: spawnableInCategory('support') },
  spatial: { title: '空间', items: spawnableInCategory('spatial') },
};

export function lookupBlock(kind: string): BlockDefinition | undefined {
  return BLOCK_CATALOG.find((b) => b.kind === kind);
}
