"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BLOCK_GROUPS = exports.BLOCK_CATALOG = void 0;
exports.lookupBlock = lookupBlock;
const DEV_BLOCKS = [];
exports.BLOCK_CATALOG = [
    { kind: 'asset-import', label: '素材导入', category: 'source', hint: '图像 / 视频 / 音频 / 3D 上传', glyph: 'Upload', accent: '#2E8B57' },
    { kind: 'mesh-import', label: '3D 导入', category: 'source', hint: 'glb/gltf/obj 等 3D 模型上传', glyph: 'Box', accent: '#5E4D8A' },
    { kind: 'mesh-viewer', label: '3D 预览', category: 'source', hint: '3D 模型预览与快照导出', glyph: 'Box', accent: '#5E4D8A' },
    { kind: 'asset-bundle', label: '素材集合', category: 'source', hint: '多素材打包排序输出', glyph: 'Images', accent: '#2E8B57' },
    { kind: 'render-slot', label: '渲染占位', category: 'source', hint: '预设 AI 结果落位框', glyph: 'ScanLine', accent: '#2E8B57' },
    { kind: 'preview-sink', label: '结果预览', category: 'source', hint: '上游结果终端预览', glyph: 'MonitorPlay', accent: '#2E8B57' },
    { kind: 'prompt', label: '提示词', category: 'generate', hint: '文本提示词输入', glyph: 'Type', accent: '#A13D63' },
    { kind: 'picture-gen', label: '图像生成', category: 'generate', hint: '多模型图像生成', glyph: 'Image', accent: '#A13D63' },
    { kind: 'clip-gen', label: '视频生成', category: 'generate', hint: 'Veo / Grok 等视频生成', glyph: 'Video', accent: '#A13D63' },
    { kind: 'clip-editor', label: '视频剪辑', category: 'generate', hint: '多片段拼接与转场', glyph: 'Scissors', accent: '#A13D63' },
    { kind: 'motion-story', label: '动效分镜', category: 'generate', hint: 'Seedance 2.0 分镜视频', glyph: 'Film', accent: '#A13D63' },
    { kind: 'director-desk', label: '导演台', category: 'generate', hint: '多镜头并发分镜生成', glyph: 'Clapperboard', accent: '#A13D63' },
    { kind: 'sound-gen', label: '音频生成', category: 'generate', hint: 'Suno 全模式音频', glyph: 'Music', accent: '#A13D63' },
    { kind: 'chat-model', label: '对话模型', category: 'generate', hint: 'LLM 流式对话', glyph: 'Brain', accent: '#A13D63' },
    { kind: 'workflow-hub', label: 'Workflow Hub', category: 'hub', hint: 'RH 工作流执行', glyph: 'Workflow', accent: '#5E4D8A' },
    { kind: 'wallet-hub', label: 'Wallet Hub', category: 'hub', hint: 'RH 钱包应用工作流', glyph: 'Wallet', accent: '#5E4D8A' },
    { kind: 'param-inject', label: '参数注入', category: 'hub', hint: 'RH 参数注入', glyph: 'Settings2', accent: '#5E4D8A', concealed: true },
    { kind: 'hub-market', label: 'Hub 超市', category: 'hub', hint: 'RH 应用启动器', glyph: 'Sparkles', accent: '#5E4D8A' },
    { kind: 'hub-toolkit', label: 'Hub 工具箱', category: 'hub', hint: '精选 RH 工具集合', glyph: 'Wrench', accent: '#5E4D8A' },
    { kind: 'vibe-workbench', label: 'Vibe 工作台', category: 'hub', hint: '嵌入 VibeX 视频工作台', glyph: 'Clapperboard', accent: '#5E4D8A' },
    ...DEV_BLOCKS,
    { kind: 'fal-market', label: 'FAL 超市', category: 'integrate', hint: 'Fal.ai 模型能力', glyph: 'Store', accent: '#5E4D8A' },
    { kind: 'grok-agent', label: 'Grok Agent', category: 'integrate', hint: 'xAI OAuth 多模态 Agent', glyph: 'Bot', accent: '#5E4D8A' },
    { kind: 'codex-agent', label: 'Codex Agent', category: 'integrate', hint: 'Codex CLI 工作台', glyph: 'TerminalSquare', accent: '#5E4D8A' },
    { kind: 'codex-picture', label: 'Codex 生图', category: 'integrate', hint: 'Codex imagegen 工作台', glyph: 'ImagePlus', accent: '#5E4D8A' },
    { kind: 'comfy-market', label: 'ComfyUI 超市', category: 'integrate', hint: 'ComfyUI 应用库', glyph: 'Boxes', accent: '#5E4D8A' },
    { kind: 'comfy-builder', label: 'ComfyUI 制作', category: 'integrate', hint: 'Workflow JSON 转应用', glyph: 'FileJson', accent: '#5E4D8A' },
    { kind: 'style-atelier', label: '风格工坊', category: 'craft', hint: '艺术家风格检索', glyph: 'Palette', accent: '#D97706' },
    { kind: 'tag-atelier', label: '标签工坊', category: 'craft', hint: '动漫标签图库', glyph: 'Tags', accent: '#D97706' },
    { kind: 'sketch-pad', label: '画板', category: 'utility', hint: '图层手绘标注', glyph: 'Pencil', accent: '#D97706' },
    { kind: 'web-view', label: '网页', category: 'utility', hint: '内嵌浏览器', glyph: 'Globe2', accent: '#D97706', concealed: true },
    { kind: 'picture-diff', label: '图像对比', category: 'utility', hint: '双图对比分析', glyph: 'GitCompare', accent: '#D97706' },
    { kind: 'frame-sampler', label: '抽帧', category: 'utility', hint: '视频抽帧', glyph: 'Scissors', accent: '#D97706', concealed: true },
    { kind: 'frame-endpoints', label: '首尾帧', category: 'utility', hint: '视频首帧/尾帧提取', glyph: 'Film', accent: '#D97706' },
    { kind: 'iterator', label: '迭代器', category: 'utility', hint: '串联/并联驱动下游', glyph: 'Repeat', accent: '#D97706' },
    { kind: 'picker', label: '选取器', category: 'utility', hint: '从集合取单项', glyph: 'Filter', accent: '#D97706' },
    { kind: 'text-chunker', label: '文本切分', category: 'utility', hint: '长文本分段', glyph: 'SplitSquareVertical', accent: '#D97706' },
    { kind: 'scale-fit', label: '尺寸调整', category: 'utility', hint: '图像缩放', glyph: 'Maximize2', accent: '#D97706' },
    { kind: 'picture-merge', label: '图像合并', category: 'utility', hint: '多图合并', glyph: 'Combine', accent: '#D97706' },
    { kind: 'bg-remove', label: '抠图', category: 'utility', hint: '背景移除', glyph: 'Eraser', accent: '#D97706', concealed: true },
    { kind: 'upscale-lite', label: '放大', category: 'utility', hint: '图像放大', glyph: 'ZoomIn', accent: '#D97706', concealed: true },
    { kind: 'grid-split', label: '宫格切分', category: 'utility', hint: '网格切图', glyph: 'Grid3x3', accent: '#D97706' },
    { kind: 'grid-compose', label: '宫格编辑', category: 'utility', hint: '宫格拼接拆分', glyph: 'LayoutGrid', accent: '#D97706' },
    { kind: 'touch-up', label: '局部编辑', category: 'support', hint: '图像局部编辑', glyph: 'Edit3', accent: '#222222', concealed: true },
    { kind: 'memo', label: '备忘', category: 'support', hint: '灵感记录', glyph: 'Lightbulb', accent: '#222222' },
    { kind: 'blueprint', label: '蓝图', category: 'support', hint: '流程蓝图', glyph: 'Map', accent: '#222222' },
    { kind: 'passthrough', label: '透传', category: 'support', hint: '数据中转', glyph: 'ArrowRightLeft', accent: '#222222' },
    { kind: 'watermark-clean', label: '去 AI 水印', category: 'support', hint: '水印/元数据清理', glyph: 'ShieldOff', accent: '#222222' },
    { kind: 'clip-sink', label: '视频输出', category: 'support', hint: '视频结果展示', glyph: 'MonitorPlay', accent: '#222222', concealed: true },
    { kind: 'cinema-prompt', label: '电影感', category: 'craft', hint: '电影感 Prompt 组合', glyph: 'Clapperboard', accent: '#D97706' },
    { kind: 'camera-prompt', label: '运镜', category: 'craft', hint: '视频运镜 Prompt', glyph: 'Camera', accent: '#D97706' },
    { kind: 'angle-visual', label: '多角度', category: 'craft', hint: '可视化角度调节', glyph: 'Compass', accent: '#D97706' },
    { kind: 'portrait-craft', label: '肖像设计', category: 'craft', hint: '肖像 Prompt 设计器', glyph: 'UserRoundCog', accent: '#D97706' },
    { kind: 'pose-craft', label: '姿势设计', category: 'craft', hint: '人体姿态编辑器', glyph: 'PersonStanding', accent: '#D97706' },
    { kind: 'link-parser', label: '链接解析', category: 'utility', hint: '自媒体链接解析', glyph: 'Link2', accent: '#D97706' },
    { kind: 'batch-runner', label: '批量处理', category: 'utility', hint: '批量素材处理', glyph: 'Files', accent: '#D97706' },
    { kind: 'topaz-picture', label: 'Topaz 图像', category: 'utility', hint: 'Topaz Gigapixel 本地放大', glyph: 'Image', accent: '#D97706' },
    { kind: 'topaz-clip', label: 'Topaz 视频', category: 'utility', hint: 'Topaz Video AI 本地放大', glyph: 'Video', accent: '#D97706' },
    { kind: 'panorama-sphere', label: '3D 全景', category: 'spatial', hint: '360° 全景预览', glyph: 'Globe2', accent: '#5E4D8A' },
    { kind: 'multi-view-3d', label: '多角度 3D', category: 'spatial', hint: '3D 多视角', glyph: 'Box', accent: '#5E4D8A', concealed: true },
    { kind: 'panorama-flat', label: '720 全景', category: 'spatial', hint: '720° 全景图', glyph: 'Globe', accent: '#5E4D8A', concealed: true },
    { kind: 'portrait-flow', label: '肖像流程', category: 'craft', hint: '肖像专用', glyph: 'UserSquare2', accent: '#5E4D8A', concealed: true },
    { kind: 'portrait-meta', label: '肖像元数据', category: 'craft', hint: '肖像参数', glyph: 'FileText', accent: '#5E4D8A', concealed: true },
    { kind: 'story-grid', label: '分镜网格', category: 'craft', hint: '分镜九宫格', glyph: 'LayoutGrid', accent: '#5E4D8A', concealed: true },
];
exports.BLOCK_GROUPS = {
    source: { title: '素材', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'source' && !b.concealed) },
    generate: { title: '生成', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'generate' && !b.concealed) },
    hub: { title: 'Hub', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'hub' && !b.concealed) },
    integrate: { title: '集成', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'integrate' && !b.concealed) },
    craft: { title: '创作', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'craft' && !b.concealed) },
    utility: { title: '工具', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'utility' && !b.concealed) },
    support: { title: '辅助', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'support' && !b.concealed) },
    spatial: { title: '空间', items: exports.BLOCK_CATALOG.filter((b) => b.category === 'spatial' && !b.concealed) },
};
function lookupBlock(kind) {
    return exports.BLOCK_CATALOG.find((b) => b.kind === kind);
}
//# sourceMappingURL=block-catalog.js.map